definitions:
  request.CustomerInfo:
    properties:
      email:
        type: string
      name:
        type: string
      phoneNumber:
        type: string
    type: object
  request.Order:
    properties:
      customerInfo:
        $ref: '#/definitions/request.CustomerInfo'
      notes:
        type: string
      orderItems:
        items:
          $ref: '#/definitions/request.OrderItem'
        type: array
      shippingInfo:
        $ref: '#/definitions/request.ShippingInfo'
    type: object
  request.OrderItem:
    properties:
      productId:
        type: string
      productSkuId:
        type: string
      quantity:
        type: integer
    type: object
  request.ShippingInfo:
    properties:
      address:
        type: string
      city:
        type: string
      district:
        type: string
      notes:
        type: string
      postalCode:
        type: string
      province:
        type: string
      recipientName:
        type: string
    type: object
  response.AuditTrail:
    properties:
      id:
        type: integer
      userName:
        type: string
    type: object
  response.Brand:
    properties:
      createdAt:
        type: string
      createdById:
        $ref: '#/definitions/response.AuditTrail'
      id:
        type: integer
      modifiedAt:
        type: string
      modifiedById:
        $ref: '#/definitions/response.AuditTrail'
      name:
        type: string
    type: object
  response.CompatibilityRule:
    properties:
      condition:
        type: string
      createdAt:
        type: string
      createdById:
        $ref: '#/definitions/response.AuditTrail'
      errorMessage:
        type: string
      id:
        type: integer
      isActive:
        type: boolean
      modifiedAt:
        type: string
      modifiedById:
        $ref: '#/definitions/response.AuditTrail'
      sourceComponentTypeCode:
        type: string
      sourceKey:
        type: string
      targetComponentTypeCode:
        type: string
      targetKey:
        type: string
      valueType:
        type: string
    type: object
  response.ComponentSpec:
    properties:
      id:
        type: string
      productSkuId:
        type: string
      specKey:
        type: string
      specValue:
        type: string
    type: object
  response.ComponentType:
    properties:
      code:
        type: string
      createdAt:
        type: string
      createdById:
        $ref: '#/definitions/response.AuditTrail'
      description:
        type: string
      id:
        type: integer
      modifiedAt:
        type: string
      modifiedById:
        $ref: '#/definitions/response.AuditTrail'
      name:
        type: string
    type: object
  response.CustomerInfo:
    properties:
      email:
        type: string
      id:
        type: string
      name:
        type: string
      phoneNumber:
        type: string
    type: object
  response.EnumResponse:
    properties:
      code:
        type: string
      name:
        type: string
    type: object
  response.Menu:
    properties:
      childs:
        items:
          $ref: '#/definitions/response.Menu'
        type: array
      createdAt:
        type: string
      createdById:
        $ref: '#/definitions/response.AuditTrail'
      id:
        type: integer
      menuItems:
        items:
          $ref: '#/definitions/response.MenuItem'
        type: array
      modifiedAt:
        type: string
      modifiedById:
        $ref: '#/definitions/response.AuditTrail'
      name:
        type: string
      parentId:
        type: integer
      path:
        type: string
    type: object
  response.MenuItem:
    properties:
      id:
        type: integer
      name:
        type: string
      productCategoryId:
        type: integer
    type: object
  response.Order:
    properties:
      code:
        type: string
      createdByCustomerAt:
        type: string
      customerId:
        type: integer
      customerInfo:
        $ref: '#/definitions/response.CustomerInfo'
      id:
        type: string
      isPaid:
        type: boolean
      modifiedByCustomerAt:
        type: string
      notes:
        type: string
      orderDate:
        type: string
      orderItems:
        items:
          $ref: '#/definitions/response.OrderItem'
        type: array
      paidAt:
        type: string
      paymentUrl:
        type: string
      shippingInfo:
        $ref: '#/definitions/response.ShippingInfo'
      status:
        $ref: '#/definitions/response.EnumResponse'
      totalPaid:
        type: number
    type: object
  response.OrderItem:
    properties:
      id:
        type: string
      orderId:
        type: string
      price:
        type: number
      product:
        $ref: '#/definitions/response.OrderItemProduct'
      productId:
        type: string
      productSkuId:
        type: string
      quantity:
        type: integer
    type: object
  response.OrderItemProduct:
    properties:
      description:
        type: string
      id:
        type: string
      imageIds:
        items:
          type: string
        type: array
      isActive:
        type: boolean
      name:
        type: string
      productSku:
        $ref: '#/definitions/response.OrderItemProductSku'
      sku:
        type: string
    type: object
  response.OrderItemProductSku:
    properties:
      id:
        type: string
      name:
        type: string
      price:
        type: number
      sku:
        type: string
      stock:
        type: integer
    type: object
  response.ProductCategory:
    properties:
      createdAt:
        type: string
      createdById:
        $ref: '#/definitions/response.AuditTrail'
      id:
        type: integer
      modifiedAt:
        type: string
      modifiedById:
        $ref: '#/definitions/response.AuditTrail'
      name:
        type: string
    type: object
  response.ProductGroupItemResponse:
    properties:
      id:
        type: string
      product:
        $ref: '#/definitions/response.ProductResponse'
      productId:
        type: string
      productSkuId:
        type: string
      qty:
        type: integer
    type: object
  response.ProductResponse:
    properties:
      brand:
        $ref: '#/definitions/response.Brand'
      componentType:
        $ref: '#/definitions/response.ComponentType'
      createdAt:
        type: string
      createdById:
        $ref: '#/definitions/response.AuditTrail'
      description:
        type: string
      id:
        type: string
      imageIds:
        items:
          type: string
        type: array
      isActive:
        type: boolean
      isShowOnlyInMarketPlace:
        type: boolean
      modifiedAt:
        type: string
      modifiedById:
        $ref: '#/definitions/response.AuditTrail'
      name:
        type: string
      productCategory:
        $ref: '#/definitions/response.ProductCategory'
      productSkuVariants:
        items:
          $ref: '#/definitions/response.ProductSkuVariant'
        type: array
      productSkus:
        items:
          $ref: '#/definitions/response.ProductSku'
        type: array
      productSpec:
        type: string
      productType:
        $ref: '#/definitions/response.EnumResponse'
      productVariantOptionValues:
        items:
          $ref: '#/definitions/response.ProductVariantOptionValue'
        type: array
      productVariantOptions:
        items:
          $ref: '#/definitions/response.ProductVariantOption'
        type: array
      sku:
        type: string
      tags:
        type: string
      videoUrl:
        type: string
    type: object
  response.ProductSku:
    properties:
      componentSpecs:
        items:
          $ref: '#/definitions/response.ComponentSpec'
        type: array
      id:
        type: string
      isActive:
        type: boolean
      name:
        type: string
      price:
        type: number
      productGroupItems:
        items:
          $ref: '#/definitions/response.ProductGroupItemResponse'
        type: array
      productId:
        type: string
      sequence:
        type: integer
      sku:
        type: string
      stock:
        type: integer
      stockAlert:
        type: integer
    type: object
  response.ProductSkuVariant:
    properties:
      id:
        type: string
      productSkuId:
        type: string
      productVariantOptionId:
        type: string
      productVariantOptionValueId:
        type: string
    type: object
  response.ProductVariantOption:
    properties:
      allowDelete:
        type: boolean
      id:
        type: string
      name:
        type: string
      productId:
        type: string
      sequence:
        type: integer
    type: object
  response.ProductVariantOptionValue:
    properties:
      allowDelete:
        type: boolean
      id:
        type: string
      name:
        type: string
      productVariantOptionId:
        type: string
      sequence:
        type: integer
    type: object
  response.ShippingInfo:
    properties:
      address:
        type: string
      city:
        type: string
      createdAt:
        type: string
      deliveredAt:
        type: string
      district:
        type: string
      estimatedDelivery:
        type: string
      id:
        type: string
      notes:
        type: string
      orderId:
        type: string
      postalCode:
        type: string
      province:
        type: string
      recipientName:
        type: string
      shippedAt:
        type: string
      shippingMethod:
        type: string
      trackingNumber:
        type: string
      updatedAt:
        type: string
    type: object
  response.WebResponse:
    properties:
      code:
        type: integer
      content: {}
      message:
        items:
          type: string
        type: array
      status:
        type: string
    type: object
info:
  contact: {}
  description: Swagger documentation for customer
  title: Customer API
  version: "1.0"
paths:
  /api/compatibility-rules:
    get:
      consumes:
      - application/json
      parameters:
      - description: ' '
        in: query
        name: sourceComponentTypeCode
        type: string
      - description: ' '
        in: query
        name: targetComponentTypeCode
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.CompatibilityRule'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/response.WebResponse'
      summary: Search compatibility rules
      tags:
      - Compatibility Rules
  /api/compatibility-rules/{id}:
    get:
      consumes:
      - application/json
      parameters:
      - description: ' '
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.CompatibilityRule'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/response.WebResponse'
      summary: Get compatibility rules by id
      tags:
      - Compatibility Rules
  /api/files:
    get:
      parameters:
      - description: File UUID without extension
        in: query
        name: id
        required: true
        type: string
      produces:
      - image/jpeg
      responses:
        "200":
          description: Photo content
          schema:
            type: string
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/response.WebResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/response.WebResponse'
      summary: Get Photo by ID
      tags:
      - File
  /api/menus:
    get:
      consumes:
      - application/json
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.Menu'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/response.WebResponse'
      summary: Search menu
      tags:
      - Menu
  /api/orders:
    post:
      consumes:
      - application/json
      parameters:
      - description: ' '
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/request.Order'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.WebResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/response.WebResponse'
      security:
      - ApiKeyAuth: []
      summary: Create order
      tags:
      - Order
  /api/orders/{code}:
    get:
      consumes:
      - application/json
      parameters:
      - description: ' '
        in: path
        name: code
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.Order'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/response.WebResponse'
      security:
      - ApiKeyAuth: []
      summary: Get order by code
      tags:
      - Order
  /api/product-categories:
    get:
      consumes:
      - application/json
      parameters:
      - collectionFormat: csv
        description: Array of IDs
        in: query
        items:
          type: integer
        name: ids
        type: array
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.ProductCategory'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/response.WebResponse'
      summary: Search product categories
      tags:
      - Product Category
  /api/product-categories/{id}:
    get:
      consumes:
      - application/json
      parameters:
      - description: ' '
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.ProductCategory'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/response.WebResponse'
      summary: Get category by id
      tags:
      - Product Category
  /api/products:
    get:
      consumes:
      - application/json
      parameters:
      - description: ' '
        in: query
        name: query
        type: string
      - collectionFormat: csv
        description: Array of Ids (1,2,3)
        in: query
        items:
          type: string
        name: ids
        type: array
      - description: ' '
        in: query
        name: productTypes
        type: string
      - description: Array of IDs (1,2,3)
        in: query
        name: componentTypeIds
        type: string
      - description: Array of IDs (1,2,3)
        in: query
        name: productCategoryIds
        type: string
      - description: Array of IDs (1,2,3)
        in: query
        name: brandIds
        type: string
      - description: String
        in: query
        name: tag
        type: string
      - description: money
        in: query
        name: minPrice
        type: number
      - description: money
        in: query
        name: maxPrice
        type: number
      - description: boolean
        in: query
        name: isInStockOnly
        type: boolean
      - description: ' '
        in: query
        name: page
        type: integer
      - description: ' '
        in: query
        name: pageSize
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/response.ProductResponse'
            type: array
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/response.WebResponse'
      summary: Search products
      tags:
      - Product
  /api/products/{id}:
    get:
      consumes:
      - application/json
      parameters:
      - description: ' '
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.ProductResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/response.WebResponse'
      summary: Get product by id
      tags:
      - Product
swagger: "2.0"
